apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstoneproject
spec:
  minReadySeconds: 60
  progressDeadlineSeconds: 600
  replicas: 8
  revisionHistoryLimit: 11
  selector:
    matchLabels:
      app: capstoneproject
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: capstoneproject
    spec:
      containers:
      - name: capstoneproject
        image: zabavnov/capstoneproject:1.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: elb
  labels:
    app: capstoneproject
spec:
  type: LoadBalancer
  ports:
  - name: "http"
    port: 80
    targetPort: 80
  selector:
    app: capstoneproject
